### ISSUE TITLE
优化小建议

### ISSUE THREAD

**Issue by sl1673495** [sanyuan0704/cloud-music#11]
排行榜页面刚进去的时候可以隐藏掉官方榜和全球榜两个title 不然挤在一起有点奇怪

**Comment by sanyuan0704** [comment]
谢谢建议！马上优化


---原始邮件---
发件人: "ssh"<notifications@github.com>
发送时间: 2019年8月16日(星期五) 下午5:24
收件人: "sanyuan0704/cloud-music"<cloud-music@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [sanyuan0704/cloud-music] 优化小建议 (#11)



排行榜页面刚进去的时候可以&#x9690;藏掉官方榜和全球榜两个title 不然挤在一起有点奇怪
 
&mdash;
