### ISSUE TITLE
运行npm install 报错

### ISSUE THREAD

**Issue by Apple9363** [sanyuan0704/cloud-music#2]
运行报错，发现第一次npm install后node_modules里面的依赖库只有一个.staging文件

! Unexpected end of JSON input while parsing near '...rElqHOGVJ3DRDcc+S+H Sj'
另一个npm install 正常，本地的node是v10

**Comment by mlqgg** [comment]
这个问题看起来像是npm下载的问题，可能是你下载过程中断网了，或者是本地的缓存有问题，可以试着清理缓存之后重新安装

**Comment by Apple9363** [comment]
安装了淘宝镜像可以了
