### ISSUE TITLE
用现有的启动脚本会出现api无法启动的情况

### ISSUE THREAD

**Issue by fanliang8023** [sanyuan0704/cloud-music#3]
用现有的启动脚本会出现api无法启动的情况，单独启动是可以起来的，需要修改一下启动端口，我个人推断应该是npm script启动脚本有一些问题。

**Comment by mlqgg** [comment]
运行npm run start 的时候，位置是在一级目录下吗？安装完 NeteaseCloudMusicApi之后需要回到主目录
```bash

**Comment by sanyuan0704** [comment]
npm script已经更新，之前是有些问题

**Comment by fanliang8023** [comment]
是的 在根目录下运行的  我看你的启动脚本是进去起了一下api  但是api没起来

**Comment by fanliang8023** [comment]
更新之后的我看可以了，两个服务都起来了

**Comment by sanyuan0704** [comment]
好的👌


---原始邮件---
发件人: "Clark"<notifications@github.com>
发送时间: 2019年8月13日(星期二) 晚上7:50
收件人: "sanyuan0704/cloud-music"<cloud-music@noreply.github.com>;
抄送: "sanyuan0704"<494130947@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [sanyuan0704/cloud-music] 用现有的启动脚本会出现api无法启动的情况 (#3)



更新之后的我看可以了，两个&#x670D;务都起来了
 
&mdash;
