### ISSUE TITLE
请问routes的属性extra是什么作用？

### ISSUE THREAD

**Issue by Y-qwq** [sanyuan0704/cloud-music#5]
我看了下react-router 和react-rouer-config的文档，都没找到这属性。
全文搜索，也没在其他地方出现。
```js
{
        path: "/recommend/",
        extra: true,
        key: 'home',
        component: Recommend,
        routes:[{
          path: '/recommend/:id',
          component: Album,
        }]
      },
```

**Comment by sanyuan0704** [comment]
不好意思，这里应该是exact，严格匹配，但这里不需要哈，我稍后删掉


---原始邮件---
发件人: "Y_qwq"<notifications@github.com>
发送时间: 2019年8月14日(星期三) 中午11:46
收件人: "sanyuan0704/cloud-music"<cloud-music@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [sanyuan0704/cloud-music] 请问routes的属性extra是什么作用？ (#5)



我看了下react-router 和react-rouer-config的文档，都没找到这属性。
 全文搜索，也没在其他地方出现。
 {         path: "/recommend/",         extra: true,         key: 'home',         component: Recommend,         routes:[{           path: '/recommend/:id',           component: Album,         }]       },
 
&mdash;

**Comment by Y-qwq** [comment]
😂好吧
