### ISSUE TITLE
一直困扰我的一个问题，为什么用了函数组件之后加载页面一个方法会被执行了几次

### ISSUE THREAD

**Issue by yzbgyq** [sanyuan0704/cloud-music#6]
![207d51ec50af96a3967625a724a666c (1)](https://user-images.githubusercontent.com/32931212/63008661-a221e880-beb5-11e9-9576-25e93d27212c.png)

**Comment by sanyuan0704** [comment]
没事，你输出一下props，看看里面的数据有哪些变化，就知道一步步更新的原因了

**Comment by sanyuan0704** [comment]
对这个页面而言，第一次页面挂载,所有数据都是初始状态，第二次bannerList更新，重新执行，第三次recommendList更新，重新执行，第四次 enterLoading更新，再次执行。顺便提一嘴，为了减少组件切换带来的重复渲染，我在useEffect里面其实是用了redux做了数据层的缓存，不知道你注意没有，这样你切到别的路由在切回来只会渲染一次。
